### ISSUE TITLE
InvokeStrategy incompatible with MessageBus

### ISSUE THREAD

**Issue by zanderbaldwin** [prooph/service-bus#120]
Prooph's invoke strategies (I'm using the [`HandleCommandStrategy`](https://github.com/prooph/service-bus/blob/master/src/Plugin/InvokeStrategy/HandleCommandStrategy.php)) determine the message name differently to how the message bus determines message names, meaning that in certain situations it is unable to map a command to a command handler (same for queries and events). I'm using the example command, [`Prooph\ServiceBus\Example\Command\EchoText`](https://github.com/prooph/service-bus/blob/master/examples/quick-start.php#L20), for this.

The `EchoText` command implements [`HasMessageName`](https://github.com/prooph/common/blob/master/src/Messaging/HasMessageName.php) but the return value of [`messageName()`](https://github.com/prooph/common/blob/master/src/Messaging/DomainMessage.php#L169) is `null`. Through the [`initialize()`](https://github.com/prooph/service-bus/blob/master/src/MessageBus.php#L77) and [`getMessageName()`](https://github.com/prooph/service-bus/blob/master/src/MessageBus.php#L186) commands, the [`MessageBus`](https://github.com/prooph/service-bus/blob/master/src/MessageBus.php) evaluates this to `Prooph\ServiceBus\Example\Command\EchoText`.

However, the invoke strategies determine the message name [using a different implementation](https://github.com/prooph/service-bus/blob/master/src/Plugin/InvokeStrategy/HandleCommandStrategy.php#L55) which directly uses the `null` value instead.
Because of this, every command object that implements `HasMessageName` but returns a null message name is always routed to `handle()` instead of (in the case of the `EchoText` command) `handleEchoText()`.

This behaviour also uses the literal string `string` inside the invoke strategy instead of the message value, when the message is of type `string`.

#### Service Definitions

```yaml
services:

    prooph.service_bus.invoke_strategy:
        class: Prooph\ServiceBus\Plugin\InvokeStrategy\HandleCommandStrategy

    prooph.service_bus.command_router:
        class: Prooph\ServiceBus\Plugin\Router\CommandRouter

    prooph.service_bus.command_bus:
        class: Prooph\ServiceBus\CommandBus
        calls:
            - [ utilize, [ "@prooph.service_bus.command_router" ]]
            - [ utilize, [ "@prooph.service_bus.invoke_strategy" ]]
```

#### EchoTextHandler.php

```php
<?php

use Prooph\ServiceBus\Example\Command\EchoText;

class EchoTextHandler
{
    public function handle(EchoText $command)
    {
        echo 'This should not be executed/echoed but it is.';
    }

    public function handleEchoText(EchoText $command)
    {
        echo $command->getText();
    }
}
```

#### main.php

```php
<?php

use Prooph\ServiceBus\Example\Command\EchoText;

$router = getFromContainer('prooph.service_bus.command_router');
$router->route(EchoText::class)->to(new EchoTextHandler);

$commandBus = getFromContainer('prooph.service_bus.command_bus');
$commandBus->dispatch(new EchoText('This is never executed/echoed.'));
```
