### ISSUE TITLE
CommanHandler is a FQCN

### ISSUE THREAD

**Issue by iaejean** [prooph/service-bus#180]
I'm having problems with a CommandHandler due in invokeStrategy or HandleCommandStrategy the $handler is a full qualified class name and not an object, then $handler is not callable or I can't call a member function handle() on string, Im using SF4 and php 7.2

**Comment by prolic** [comment]
Use the service locator plugin and a dic to resolve the class name to the
object.

**Comment by iaejean** [comment]
Thanks, I found my problem with the bundle settings, I should add my handlers as publics 

```yaml
    App\Domain\Command\:
        resource: '../src/Domain/Command/*Handler.php'
        public: true
        tags:
            - { name: 'prooph_service_bus.app_domain_command_bus.route_target', message_detection: true }
```
